### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3

### ISSUE THREAD

**Issue by hochhaus** [google/safe-html-types#1]
When using the [1.0.5 maven jar](http://repo1.maven.org/maven2/com/google/common/html/types/types/1.0.5/types-1.0.5.jar) I receive the following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.google.template.soy.types.proto.SafeStringTypes.<clinit>(SafeStringTypes.java:38)
        at com.google.template.soy.types.proto.SoyProtoTypeProvider.<init>(SoyProtoTypeProvider.java:186)
        at com.google.template.soy.types.proto.SoyProtoTypeProvider.<init>(SoyProtoTypeProvider.java:55)
        at com.google.template.soy.types.proto.SoyProtoTypeProvider$Builder.build(SoyProtoTypeProvider.java:120)
        at com.google.template.soy.AbstractSoyCompiler.doMain(AbstractSoyCompiler.java:176)
        at com.google.template.soy.AbstractSoyCompiler.access$000(AbstractSoyCompiler.java:49)
        at com.google.template.soy.AbstractSoyCompiler$2.main(AbstractSoyCompiler.java:149)
        at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:255)
        at com.google.template.soy.AbstractSoyCompiler.run(AbstractSoyCompiler.java:146)
        at com.google.template.soy.AbstractSoyCompiler.runMain(AbstractSoyCompiler.java:138)
        at com.google.template.soy.SoyToIncrementalDomSrcCompiler.main(SoyToIncrementalDomSrcCompiler.java:64)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.GeneratedMessageV3
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

This was not present when using 1.0.4. Let me know if you need any additional information.

**Comment by jart** [comment]
This probably isn't an issue with safe-html-types. I'm doing some work on the Closure Rules code. I managed to get this updated. I ran into the same error a couple times. But it was because I had a version of protobuf_java older than 3.1.0 on the classpath. Now that Closure Rules is upgraded, we should be good.

This issue can be closed.

**Comment by hochhaus** [comment]
Thanks @jart. Closing...

**Comment by jart** [comment]
Related: https://github.com/bazelbuild/rules_closure/commit/3c51806e4018e587a722bf13e1018b09936cf9fa

**Comment by premsanth-rajamani** [comment]
@jart worked perfectly, thanks a lot 👍
